language: ruby
services:
  - docker

script:
  - version=${TRAVIS_TAG-latest} ;
    if [ "$TRAVIS_TAG" == "" ]; then
    version=latest;
    fi ;
    docker build --build-arg GITHUB_OAUTH=${GITHUB_OAUTH} --build-arg AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --build-arg AWS_SECRET_KEY=${AWS_SECRET_KEY} --build-arg EULA=${EULA} --build-arg AWS_REGION=${AWS_REGION}  -t build-image . ;
    docker create --name=build-container build-image cat;
    docker cp build-container:/usr/src/mcserver/. ./mcserver;
    docker cp build-container:/usr/bin/startserver ./mcserver;
    docker build -f Dockerfile.release -t exorath/server-bc:${version} .

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -u=exorath -p="$DOCKER_PASSWORD";
    echo "version $TRAVIS_TAG" ;
    docker push "exorath/server-bc:$TRAVIS_TAG" ;
    fi 
