apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: server-bc
    type: bc
  name: server-bc
  namespace: servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-bc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server-bc
    spec:
      containers:
      - image: exorath/server-bc:0.0.39
        imagePullPolicy: IfNotPresent
        name: server-bc
        ports:
        - containerPort: 25565
          protocol: TCP
        env:
        - name: ACTIONAPI_SERVICE_ADDRESS
          value: "actionapiservice:8080"
        - name: CONNECTOR_SERVICE_ADDRESS
          value: "http://connectorservice:8080"
        stdin: true
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 1000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-bc
    type: bc
  name: server-bc
  namespace: servers
spec:
  selector:
    app: server-bc
  ports:
  - protocol: TCP
    port: 25565
    targetPort: 25565
  type: NodePort
